language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env: MINIMUM_VERSIONS=false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.1
      env: MINIMUM_VERSIONS=true

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - if [[ $MINIMUM_VERSIONS = false ]]; then travis_retry composer install; fi
  - if [[ $MINIMUM_VERSIONS = true ]]; then travis_retry composer update --no-interaction --prefer-lowest; fi

script:
  - ./vendor/bin/phpcs --standard=psr2 src/
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
